development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: time_to_answer

test:
  adapter: redis
  url: redis://localhost:6379/0

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: time_to_answer_production
